version: "3.1"
services:
  mongo:
    image: "mongo:5.0.12"
    container_name: "chat-app-mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root4242
    ports:
      - 27017:27017
